name: stop_watch_timer
description: This is Stop Watch Timer for flutter plugin. It easily create application of stop watch for sports if use this plugin.
version: 0.1.2+1
homepage: https://twitter.com/hobbydevelop
repository: https://github.com/hukusuke1007/stop_watch_timer

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  plugin:
    androidPackage: com.gmail.hukusuke1007.stop_watch_timer
    pluginClass: StopWatchTimerPlugin

